version: "3.8"

services:
  backend:
    build: ./server
    container_name: openquizzer_backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build: ./client/frontend
    container_name: openquizzer_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
